const MESSAGES = {
    ADDRESS_NOT_FOUND: "Address not found",
    ADMIN_AUTH_ERROR: "Admin Auth Error",
    AJAX_AUTH_ERROR: "Ajax Auth Error",
    AN_ERROR_OCCURED_PLEASE_TRY_AGAIN: "An error occured please try again",
    AN_ERROR_OCCURRED_WHILE_ADDING_TO_CART: "An error occurred while adding to cart",
    AN_ERROR_OCCURRED_WHILE_APPLYING_THE_COUPON: "An error occurred while applying the coupon",
    AN_ERROR_OCCURRED_WHILE_CHANGING_THE_PASSWORD: "An error occurred while changing the password.",
    AN_ERROR_OCCURRED_WHILE_DELETING_THE_IMAGE: "An error occurred while deleting the image",
    AN_ERROR_OCCURRED_WHILE_REMOVING_THE_PRODUCT_FROM_: "An error occurred while removing the product from cart",
    AN_ERROR_OCCURRED_WHILE_UPDATING_THE_CART: "An error occurred while updating the cart",
    AN_ERROR_OCCURRED_WHILE_UPDATING_THE_PRODUCT: "An error occurred while updating the product",
    AN_ERROR_OCCURRED_WHILE_UPDATING_YOUR_PROFILE: "An error occurred while updating your profile",
    AN_ERROR_OCCURRED_WHILE_UPDATING_YOUR_PROFILE_IMAG: "An error occurred while updating your profile image",
    CANNOT_ADD_MORE_PRODUCT_IS_OUT_OF_STOCK: "Cannot add more, product is out of stock",
    CANNOT_REVERT_ORDER_TO_A_PREVIOUS_STATUS: "Cannot revert order to a previous status",
    CANNOT_UPDATE_CANCELLED_ORDER: "Cannot update cancelled order",
    CART_IS_EMPTY: "Cart is empty",
    CART_UPDATED: "Cart updated",
    CATEGORY_ADDED_SUCCESSFULLY: "Category added successfully",
    CATEGORY_DELETED_SUCCESSFULLY: "Category deleted successfully",
    CATEGORY_LISTED_SUCCESSFULLY: "Category listed successfully",
    CATEGORY_NAME_CANNOT_BE_EMPTY: "Category name cannot be empty",
    CATEGORY_NOT_FOUND: "Category not found",
    CATEGORY_UNLISTED_SUCCESSFULLY: "Category unlisted successfully",
    CATEGORY_UPDATED_SUCCESSFULLY: "Category updated successfully",
    CATEGORY_WITH_THIS_NAME_ALREADY_EXISTS: "Category with this name already exists",
    COD_NOT_AVAILABLE_FOR_ORDERS_ABOVE_35_000: "COD not available for orders above ₹35,000",
    COMMENT_ADDED_SUCCESSFULLY: "Comment added successfully",
    COMMENT_BLOCKED_SUCCESSFULLY: "Comment blocked successfully",
    COMMENT_CANNOT_BE_EMPTY: "Comment cannot be empty",
    COMMENT_DELETED_SUCCESSFULLY: "Comment deleted successfully",
    COMMENT_IS_TOO_LONG_MAXIMUM_500_CHARACTERS: "Comment is too long (maximum 500 characters)",
    COMMENT_NOT_FOUND_OR_YOU_ARE_NOT_AUTHORIZED_TO_DEL: "Comment not found or you are not authorized to delete this comment",
    COMMENT_UNBLOCKED_SUCCESSFULLY: "Comment unblocked successfully",
    COUPON_DELETED_SUCCESSFULLY: "Coupon deleted successfully",
    COUPON_HAS_EXPIRED: "Coupon has expired",
    COUPON_NOT_FOUND: "Coupon not found",
    COUPON_UPDATED_SUCCESSFULLY: "Coupon updated successfully",
    CURRENT_PASSWORD_IS_INCORRECT: "Current password is incorrect.",
    DASHBOARD_ERROR: "Dashboard Error:",
    DESCRIPTION_IS_REQUIRED: "Description is required",
    EMAIL_NOT_FOUND_IN_SESSION: "Email not found in session",
    EMAIL_SENT: "Email sent:",
    ERROR: "Error:",
    ERROR_ADDING_ADDRESS: "Error adding address",
    ERROR_APPLYING_COUPON: "Error applying coupon:",
    ERROR_CANCELLING_ORDER: "Error cancelling order:",
    ERROR_CHANGING_PASSWORD: "Error changing password:",
    ERROR_CHECKING_BLOCKED_USER: "Error checking blocked user:",
    ERROR_CHECKING_STOCK: "Error checking stock:",
    ERROR_CHECKING_STOCK_AVAILABILITY: "Error checking stock availability",
    ERROR_CREATING_MANUAL_TRANSACTION: "Error creating manual transaction:",
    ERROR_CREATING_RAZORPAY_ORDER: "Error creating Razorpay order:",
    ERROR_CREATING_SALE_RECORD: "Error creating sale record:",
    ERROR_CREATING_TRANSACTION: "Error creating transaction:",
    ERROR_CREATING_TRANSACTION_RECORD: "Error creating transaction record:",
    ERROR_DELETING_COUPON: "Error Deleting Coupon",
    ERROR_DELETING_OLD_PROFILE_IMAGE: "Error deleting old profile image:",
    ERROR_DELETING_TEMPORARY_FILE: "Error deleting temporary file:",
    ERROR_FETCHING_ORDER_DETAILS: "Error fetching order details:",
    ERROR_FETCHING_ORDERS: "Error fetching orders:",
    ERROR_FETCHING_PRODUCTS: "Error fetching products:",
    ERROR_FETCHING_TRANSACTION_DETAILS: "Error fetching transaction details:",
    ERROR_FETCHING_TRANSACTIONS: "Error fetching transactions:",
    ERROR_FOR_FETCHING_PRODUCT_DETAILS: "Error for fetching product details",
    ERROR_FOR_SENDING_EMAIL: "Error for sending email",
    ERROR_GENERATING_INVOICE: "Error generating invoice:",
    ERROR_GETTING_ORDER_STATUS_COUNTS: "Error getting order status counts:",
    ERROR_GETTING_RECENT_ORDERS: "Error getting recent orders:",
    ERROR_GETTING_SALES_DATA: "Error getting sales data:",
    ERROR_GETTING_TOP_PRODUCTS: "Error getting top products:",
    ERROR_GETTING_TRANSACTION_STATS: "Error getting transaction stats:",
    ERROR_HANDLING_RETURN_REQUEST: "Error handling return request:",
    ERROR_IN_ADDCATEGORY: "Error in addCategory:",
    ERROR_IN_ADDCATEGORYOFFER: "Error in addCategoryOffer:",
    ERROR_IN_ADDCOMMENT: "Error in addComment:",
    ERROR_IN_ADDPRODUCTOFFER: "Error in addProductOffer:",
    ERROR_IN_ADDRESS_LOADING: "Error in Address loading",
    ERROR_IN_ADDTOCART: "Error in addToCart:",
    ERROR_IN_ADDTOWISHLIST: "Error in addToWishlist:",
    ERROR_IN_BLOCKCOMMENT: "Error in blockComment:",
    ERROR_IN_CANCELORDER: "Error in cancelOrder:",
    ERROR_IN_CANCELRETURNREQUEST: "Error in cancelReturnRequest:",
    ERROR_IN_CHANGEQUANTITY: "Error in changeQuantity:",
    ERROR_IN_CREATERAZORPAYORDER: "Error in createRazorpayOrder:",
    ERROR_IN_DELETECATEGORY: "Error in deleteCategory:",
    ERROR_IN_DELETECOMMENT: "Error in deleteComment:",
    ERROR_IN_DELETEPRODUCT: "Error in deleteProduct:",
    ERROR_IN_DELETESINGLEIMAGE: "Error in deleteSingleImage:",
    ERROR_IN_DELETING_IN_ADDRESS: "Error in deleting in address",
    ERROR_IN_EDIT_ADDRESS: "Error in edit Address",
    ERROR_IN_EDITCATEGORYOFFER: "Error in editCategoryOffer:",
    ERROR_IN_EDITING_ADDRESS: "Error in editing address",
    ERROR_IN_EDITPRODUCT: "Error in editProduct:",
    ERROR_IN_GETALLCOMMENTS: "Error in getAllComments:",
    ERROR_IN_GETCARTPAGE: "Error in getCartPage:",
    ERROR_IN_GETEDITPRODUCT: "Error in getEditProduct:",
    ERROR_IN_GETORDERS: "Error in getOrders:",
    ERROR_IN_GETPRODUCTCOMMENTS: "Error in getProductComments:",
    ERROR_IN_GETSALESDATA_API: "Error in getSalesData API:",
    ERROR_IN_GETTOPSELLING_API: "Error in getTopSelling API:",
    ERROR_IN_LOADCHECKOUTPAGE: "Error in loadCheckoutPage:",
    ERROR_IN_LOADCOUPONS: "Error in loadCoupons:",
    ERROR_IN_LOADORDERDETAILS: "Error in loadOrderDetails:",
    ERROR_IN_LOADSALESPAGE: "Error in loadSalesPage:",
    ERROR_IN_PAYMENTFAILURE: "Error in paymentFailure:",
    ERROR_IN_PLACEORDER: "Error in placeOrder:",
    ERROR_IN_PLACEWALLETORDER: "Error in placeWalletOrder:",
    ERROR_IN_REMOVECATEGORYOFFER: "Error in removeCategoryOffer:",
    ERROR_IN_REMOVEPRODUCTOFFER: "Error in removeProductOffer:",
    ERROR_IN_REND_OTP: "Error in rend otp",
    ERROR_IN_REPAYORDER: "Error in repayOrder:",
    ERROR_IN_REQUESTRETURN: "Error in requestReturn:",
    ERROR_IN_UNBLOCKCOMMENT: "Error in unblockComment:",
    ERROR_IN_VERIFYPAYMENT: "Error in verifyPayment:",
    ERROR_LOADING_PRODUCT_ADD_PAGE: "Error loading product add page",
    ERROR_LOADING_PRODUCT_ADD_PAGE_1: "Error loading product add page:",
    ERROR_LOADING_SALES_REPORT: "Error loading sales report",
    ERROR_LOADING_SHOPPING_PAGE: "Error loading shopping page:",
    ERROR_LOADING_WALLET: "Error loading wallet:",
    ERROR_PROCESSING_REFUND: "Error processing refund:",
    ERROR_RESENDING_OTP: "Error Resending OTP",
    ERROR_SAVING_IMAGE: "Error saving image",
    ERROR_SAVING_IMAGE_1: "Error saving image:",
    ERROR_SAVING_PRODUCT: "Error saving product",
    ERROR_SAVING_PRODUCT_1: "Error saving product:",
    ERROR_SEARCHING_PRODUCTS: "Error searching products:",
    ERROR_SENDING_EMAIL: "error sending email",
    ERROR_SENDING_FILE: "Error sending file:",
    ERROR_UPDATING_COUPON: "Error updating coupon",
    ERROR_UPDATING_COUPON_1: "Error updating coupon:",
    ERROR_UPDATING_ORDER_STATUS: "Error updating order status:",
    ERROR_UPDATING_PROFILE: "Error updating profile:",
    ERROR_UPDATING_PROFILE_IMAGE: "Error updating profile image:",
    ERROR_UPDATING_RETURN_STATUS: "Error updating return status:",
    ERROR_VERIFYING_OTP: "Error verifying OTP",
    ERROR_VERIFYING_PAYMENT: "Error verifying payment:",
    ERROR_WHILE_FILTERING_PRODUCTS: "Error while filtering products:",
    ERROR_WITHDRAWING_MONEY: "Error withdrawing money:",
    FAILED_TO_ADD_CATEGORY: "Failed to add category",
    FAILED_TO_CREATE_ORDER: "Failed to create order",
    FAILED_TO_DELETE_CATEGORY: "Failed to delete category",
    FAILED_TO_FETCH_CATEGORY: "Failed to fetch category",
    FAILED_TO_INITIATE_PAYMENT: "Failed to initiate payment",
    FAILED_TO_LIST_CATEGORY: "Failed to list category",
    FAILED_TO_PLACE_ORDER: "Failed to place order",
    FAILED_TO_PROCESS_REFUND: "Failed to process refund",
    FAILED_TO_RESEND_OTP_PLEASE_TRY_AGAIN: "Failed to resend OTP Please try again",
    FAILED_TO_SEND_OTP_PLEASE_TRY_AGAIN: "Failed to send OTP. PLease try again",
    FAILED_TO_UNLIST_CATEGORY: "Failed to unlist category",
    FAILED_TO_UPDATE_CATEGORY: "Failed to update category",
    GOOGLE_LOGIN_ERROR: "Google login error:",
    HOME_PAGE_NOT_FOUND: "Home Page Not Found",
    IMAGE_DELETED_SUCCESSFULLY: "Image deleted successfully",
    IMAGE_SAVED_SUCCESSFULLY: "Image saved successfully",
    INSUFFICIENT_BALANCE: "Insufficient balance",
    INSUFFICIENT_WALLET_BALANCE: "Insufficient wallet balance",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    INTERNAL_SERVER_ERROR_1: "Internal server error",
    INTERNAL_SERVER_ERROR_PLEASE_TRY_AGAIN: "INternal Server Error, Please try again",
    INTERNAL_SERVER_ERRRO: "Internal server errro",
    INVALID_ACTION: "Invalid action",
    INVALID_AMOUNT: "Invalid amount",
    INVALID_COUPON_CODE: "Invalid coupon code",
    INVALID_COUPON_ID: "Invalid coupon ID",
    INVALID_OTP_PLEASE_TRY_AGAIN: "Invalid OTP Please try again",
    INVALID_PASSWORD: "Invalid Password",
    INVALID_PAYMENT_SIGNATURE: "Invalid payment signature",
    INVALID_PERCENTAGE_VALUE: "Invalid percentage value",
    INVALID_REQUEST_DATA: "Invalid request data",
    INVALID_SIGNATURE: "Invalid signature",
    LOCAL_UNLINK_ERROR: "Local unlink error:",
    LOGIN_ERROR: "Login Error",
    LOGIN_FAILED_TRY_AGAIN: "Login Failed Try again",
    LOGOUT_ERROR: "Logout Error",
    MAXIMUM_5_QUANTITY_PER_USER_REACHED: "Maximum 5 quantity per user reached",
    MONEY_WITHDRAWN_SUCCESSFULLY: "Money withdrawn successfully",
    NO_IMAGE_FILE_PROVIDED: "No image file provided",
    NO_IMAGE_PROVIDED: "No image provided",
    OFFER_ADDED_SUCCESSFULLY: "Offer added successfully",
    OFFER_REMOVED_SUCCESSFULLY: "Offer removed successfully",
    OFFER_UPDATED_SUCCESSFULLY: "Offer updated successfully",
    ORDER_CANCELLED_AND_REFUND_PROCESSED_SUCCESSFULLY: "Order cancelled and refund processed successfully",
    ORDER_CANCELLED_SUCCESSFULLY: "Order cancelled successfully",
    ORDER_CANNOT_BE_CANCELLED: "Order cannot be cancelled",
    ORDER_CANNOT_BE_REPAID: "Order cannot be repaid",
    ORDER_IS_NOT_ELIGIBLE_FOR_RETURN: "Order is not eligible for return",
    ORDER_MUST_BE_IN_RETURNING_STATUS_FIRST: "Order must be in returning status first",
    ORDER_NOT_FOUND: "Order not found",
    ORDER_STATUS_UPDATED_SUCCESSFULLY: "Order status updated successfully",
    ORDERS_NOT_FOUND: "Orders not found",
    ORDERS_PLACED_SUCCESSFULLY: "Orders placed successfully",
    OTP: "OTP: ",
    OTP_1: "OTP",
    OTP_NOT_MATCHING: "OTP not Matching",
    OTP_NOT_MATCHING_2: "OTP not matching",
    OTP_RESEND_SUCCESSFULLY: "OTP Resend Successfully",
    OTP_SEND: "OTP Send",
    PASSWORD_CHANGED_SUCCESSFULLY: "Password changed successfully.",
    PASSWORD_DO_NOT_MATCH: "Password do not match",
    PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS_LONG_AND_CO: "Password must be at least 8 characters long and contain both letters and numbers.",
    PASSWORD_NOT_MATCHED: "Password not matched",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match.",
    PAYMENT_TIME_LIMIT_EXCEEDED_15_MINS_ORDER_CANCELLE: "Payment time limit exceeded (15 mins). Order cancelled.",
    PAYMENT_VERIFICATION_FAILED: "Payment verification failed",
    PAYMENT_VERIFIED_AND_WALLET_UPDATED_SUCCESSFULLY: "Payment verified and wallet updated successfully",
    PAYMENT_VERIFIED_SUCCESSFULLY: "Payment verified successfully",
    PLEASE_ENTER_A_VALID_10_DIGIT_PHONE_NUMBER: "Please enter a valid 10-digit phone number",
    PLEASE_UPLOAD_ALL_4_PRODUCT_IMAGES: "Please upload all 4 product images",
    PRODUCT_ADDED_SUCCESSFULLY: "Product added successfully",
    PRODUCT_ADDED_TO_CART: "Product added to cart",
    PRODUCT_ADDED_TO_WISHLIST: "Product Added to Wishlist",
    PRODUCT_ALREADY_EXISTS_TRY_ANOTHER_NAME: "Product already exists, try another name",
    PRODUCT_ALREADY_IN_WISHLIST: "Product Already in Wishlist",
    PRODUCT_ID_IS_REQUIRED: "Product ID is required",
    PRODUCT_IS_OUT_OF_STOCK: "Product is out of stock",
    PRODUCT_NOT_FOUND: "Product not found",
    PRODUCT_NOT_FOUND_IN_CART: "Product not found in cart",
    PRODUCT_REMOVED_FROM_CART: "Product removed from cart",
    PRODUCT_REMOVED_FROM_CART_DUE_TO_ZERO_STOCK: "Product removed from cart due to zero stock",
    PRODUCT_UPDATED_SUCCESSFULLY: "Product updated successfully",
    PRODUCT_WITH_THIS_NAME_ALREADY_EXISTS_PLEASE_TRY_A: "Product with this name already exists. Please try another name.",
    PROFILE_IMAGE_UPDATED_SUCCESSFULLY: "Profile image updated successfully",
    PROFILE_UPDATED_SUCCESSFULLY: "Profile updated successfully",
    RESEND_OTP: "Resend Otp: ",
    RESEND_OTP_1: "Resend OTP",
    RESEND_OTP_SUCCESSFUL: "Resend OTP Successful",
    RESENDED_OTP: "Resended OTP:",
    RESENDING_OTP_TO_EMAIL: "Resending otp to email",
    RETURN_REQUEST_CANCELLED_SUCCESSFULLY: "Return request cancelled successfully",
    RETURN_REQUEST_CANNOT_BE_CANCELLED: "Return request cannot be cancelled",
    RETURN_REQUEST_SUBMITTED_SUCCESSFULLY: "Return request submitted successfully",
    RETURN_STATUS_UPDATED_SUCCESSFULLY: "Return status updated successfully",
    SERVER_ERROR: "Server Error",
    SERVER_ERROR_3: "Server error",
    SERVER_IS_RUNNING_ON_PORT_HTTP_LOCALHOST_3999: "Server is running on port http://localhost:3999",
    SIGN_UP_PAGE_NOT_FOUND: "Sign Up Page Not Found",
    SIGNUP_ERROR: "signup error",
    TRANSACTION_CREATED_SUCCESSFULLY: "Transaction created successfully",
    UPDATED_PAYMENT_STATUS_TO_FAILED: "Updated payment status to Failed",
    USER_ALREADY_EXISTS: "User already exists",
    USER_AUTH_ERROR: "User Auth Error",
    USER_IS_BLOCKED_BY_ADMIN: "User is Blocked by Admin",
    USER_IS_BLOCKED_OR_NOT_FOUND: "User is blocked or not found",
    USER_NOT_FOUND: "User not found",
    USER_NOT_FOUND_4: "User not found.",
    USER_NOT_LOGGED_IN: "User not logged in",
    USER_OR_PRODUCT_NOT_FOUND: "User or Product not found",
    USER_WITH_EMAIL_NOT_EXIST: "User with email not exist",
    USER_WITH_THIS_EMAIL_DOES_NOT_EXIST: "User with this email does not exist",
    USERNAME_IS_ALREADY_TAKEN_PLEASE_CHOOSE_A_DIFFEREN: "Username is already taken. Please choose a different one.",
    YOU_HAVE_ALREADY_USED_THIS_COUPON: "You have already used this coupon",
    YOU_HAVE_REACHED_THE_MAXIMUM_LIMIT_OF_3_COMMENTS_P: "You have reached the maximum limit of 3 comments per day"
};

export default MESSAGES;